// 小学常用汉字（按年级，含拼音与组词）
const CHINESE_DB = {
  "一年级": [
    { char: "一", pinyin: "yī", words: ["一个", "一起"] },
    { char: "二", pinyin: "èr", words: ["二月", "第二"] },
    { char: "三", pinyin: "sān", words: ["三个", "三月"] },
    { char: "四", pinyin: "sì", words: ["四月", "四个"] },
    { char: "五", pinyin: "wǔ", words: ["五月", "五个"] },
    { char: "六", pinyin: "liù", words: ["六月", "六个"] },
    { char: "七", pinyin: "qī", words: ["七月", "七个"] },
    { char: "八", pinyin: "bā", words: ["八月", "八个"] },
    { char: "九", pinyin: "jiǔ", words: ["九月", "九个"] },
    { char: "十", pinyin: "shí", words: ["十月", "十个"] },
    { char: "人", pinyin: "rén", words: ["人们", "大人"] },
    { char: "大", pinyin: "dà", words: ["大小", "大家"] },
    { char: "小", pinyin: "xiǎo", words: ["小心", "小学"] },
    { char: "上", pinyin: "shàng", words: ["上下", "上学"] },
    { char: "下", pinyin: "xià", words: ["下山", "下面"] },
    { char: "日", pinyin: "rì", words: ["日出", "生日"] },
    { char: "月", pinyin: "yuè", words: ["月亮", "月光"] },
    { char: "水", pinyin: "shuǐ", words: ["水果", "河水"] },
    { char: "火", pinyin: "huǒ", words: ["火车", "大火"] },
    { char: "山", pinyin: "shān", words: ["山上", "山水"] },
    { char: "石", pinyin: "shí", words: ["石头", "石子"] },
    { char: "木", pinyin: "mù", words: ["木头", "树木"] },
    { char: "田", pinyin: "tián", words: ["田地", "田野"] },
    { char: "土", pinyin: "tǔ", words: ["土地", "泥土"] },
    { char: "口", pinyin: "kǒu", words: ["人口", "门口"] },
    { char: "目", pinyin: "mù", words: ["目光", "节目"] },
    { char: "耳", pinyin: "ěr", words: ["耳朵", "耳目"] },
    { char: "手", pinyin: "shǒu", words: ["双手", "小手"] },
    { char: "足", pinyin: "zú", words: ["手足", "十足"] },
    { char: "鸟", pinyin: "niǎo", words: ["小鸟", "飞鸟"] },
    { char: "鱼", pinyin: "yú", words: ["小鱼", "金鱼"] },
    { char: "虫", pinyin: "chóng", words: ["小虫", "虫子"] },
    { char: "云", pinyin: "yún", words: ["白云", "云朵"] },
    { char: "雨", pinyin: "yǔ", words: ["下雨", "雨水"] },
    { char: "风", pinyin: "fēng", words: ["大风", "风雨"] },
    { char: "花", pinyin: "huā", words: ["花朵", "花园"] },
    { char: "草", pinyin: "cǎo", words: ["小草", "草地"] },
    { char: "天", pinyin: "tiān", words: ["天空", "今天"] },
    { char: "地", pinyin: "dì", words: ["大地", "地方"] },
    { char: "中", pinyin: "zhōng", words: ["中国", "中间"] },
    { char: "国", pinyin: "guó", words: ["中国", "国家"] },
    { char: "我", pinyin: "wǒ", words: ["我们", "我家"] },
    { char: "你", pinyin: "nǐ", words: ["你们", "你好"] },
    { char: "他", pinyin: "tā", words: ["他们", "他的"] },
    { char: "她", pinyin: "tā", words: ["她们", "她的"] },
    { char: "好", pinyin: "hǎo", words: ["好人", "好的"] },
    { char: "不", pinyin: "bù", words: ["不好", "不行"] },
    { char: "有", pinyin: "yǒu", words: ["没有", "只有"] },
    { char: "是", pinyin: "shì", words: ["不是", "是的"] },
    { char: "来", pinyin: "lái", words: ["出来", "回来"] },
    { char: "去", pinyin: "qù", words: ["出去", "回去"] },
    { char: "白", pinyin: "bái", words: ["白天", "白云"] },
    { char: "红", pinyin: "hóng", words: ["红色", "红花"] },
    { char: "黄", pinyin: "huáng", words: ["黄色", "黄河"] },
    { char: "绿", pinyin: "lǜ", words: ["绿色", "绿叶"] },
    { char: "蓝", pinyin: "lán", words: ["蓝色", "蓝天"] },
    { char: "多", pinyin: "duō", words: ["多少", "很多"] },
    { char: "少", pinyin: "shǎo", words: ["多少", "少年"] },
    { char: "开", pinyin: "kāi", words: ["开心", "打开"] },
    { char: "心", pinyin: "xīn", words: ["开心", "爱心"] },
    { char: "看", pinyin: "kàn", words: ["看见", "好看"] },
    { char: "听", pinyin: "tīng", words: ["听见", "听话"] },
    { char: "说", pinyin: "shuō", words: ["说话", "听说"] },
    { char: "写", pinyin: "xiě", words: ["写字", "写完"] },
    { char: "读", pinyin: "dú", words: ["读书", "朗读"] },
    { char: "学", pinyin: "xué", words: ["学习", "学生"] },
    { char: "校", pinyin: "xiào", words: ["学校", "校园"] },
    { char: "爸", pinyin: "bà", words: ["爸爸"] },
    { char: "妈", pinyin: "mā", words: ["妈妈"] },
    { char: "哥", pinyin: "gē", words: ["哥哥"] },
    { char: "姐", pinyin: "jiě", words: ["姐姐"] },
    { char: "弟", pinyin: "dì", words: ["弟弟"] },
    { char: "妹", pinyin: "mèi", words: ["妹妹"] },
    { char: "家", pinyin: "jiā", words: ["家人", "回家"] },
    { char: "门", pinyin: "mén", words: ["大门", "门口"] },
    { char: "车", pinyin: "chē", words: ["汽车", "火车"] },
    { char: "书", pinyin: "shū", words: ["读书", "书包"] },
    { char: "笔", pinyin: "bǐ", words: ["铅笔", "毛笔"] },
    { char: "纸", pinyin: "zhǐ", words: ["白纸", "纸张"] },
    { char: "春", pinyin: "chūn", words: ["春天", "春节"] },
    { char: "夏", pinyin: "xià", words: ["夏天", "夏日"] },
    { char: "秋", pinyin: "qiū", words: ["秋天", "秋风"] },
    { char: "冬", pinyin: "dōng", words: ["冬天", "冬日"] },
    { char: "东", pinyin: "dōng", words: ["东方", "东西"] },
    { char: "西", pinyin: "xī", words: ["西方", "东西"] },
    { char: "南", pinyin: "nán", words: ["南方", "南边"] },
    { char: "北", pinyin: "běi", words: ["北方", "北京"] },
    { char: "飞", pinyin: "fēi", words: ["飞机", "飞鸟"] },
    { char: "走", pinyin: "zǒu", words: ["走路", "走开"] },
    { char: "跑", pinyin: "pǎo", words: ["跑步", "快跑"] },
    { char: "跳", pinyin: "tiào", words: ["跳高", "跳舞"] },
    { char: "笑", pinyin: "xiào", words: ["微笑", "好笑"] },
    { char: "哭", pinyin: "kū", words: ["哭泣", "哭闹"] },
    { char: "吃", pinyin: "chī", words: ["吃饭", "好吃"] },
    { char: "喝", pinyin: "hē", words: ["喝水", "喝茶"] },
    { char: "玩", pinyin: "wán", words: ["玩具", "好玩"] },
    { char: "爱", pinyin: "ài", words: ["爱心", "可爱"] }
  ],
  "二年级": [
    { char: "明", pinyin: "míng", words: ["明天", "光明"] },
    { char: "星", pinyin: "xīng", words: ["星星", "明星"] },
    { char: "光", pinyin: "guāng", words: ["阳光", "光明"] },
    { char: "阳", pinyin: "yáng", words: ["太阳", "阳光"] },
    { char: "清", pinyin: "qīng", words: ["清水", "清楚"] },
    { char: "静", pinyin: "jìng", words: ["安静", "静静"] },
    { char: "美", pinyin: "měi", words: ["美丽", "美好"] },
    { char: "丽", pinyin: "lì", words: ["美丽", "秀丽"] },
    { char: "高", pinyin: "gāo", words: ["高山", "高兴"] },
    { char: "兴", pinyin: "xìng", words: ["高兴", "兴奋"] },
    { char: "快", pinyin: "kuài", words: ["快乐", "很快"] },
    { char: "乐", pinyin: "lè", words: ["快乐", "音乐"] },
    { char: "友", pinyin: "yǒu", words: ["朋友", "友谊"] },
    { char: "朋", pinyin: "péng", words: ["朋友"] },
    { char: "树", pinyin: "shù", words: ["大树", "树木"] },
    { char: "叶", pinyin: "yè", words: ["树叶", "绿叶"] },
    { char: "河", pinyin: "hé", words: ["小河", "河流"] },
    { char: "海", pinyin: "hǎi", words: ["大海", "海边"] },
    { char: "浪", pinyin: "làng", words: ["波浪", "浪花"] },
    { char: "沙", pinyin: "shā", words: ["沙子", "沙滩"] },
    { char: "金", pinyin: "jīn", words: ["金子", "金色"] },
    { char: "银", pinyin: "yín", words: ["银行", "银色"] },
    { char: "城", pinyin: "chéng", words: ["城市", "长城"] },
    { char: "乡", pinyin: "xiāng", words: ["家乡", "乡村"] },
    { char: "路", pinyin: "lù", words: ["马路", "走路"] },
    { char: "桥", pinyin: "qiáo", words: ["大桥", "桥上"] },
    { char: "房", pinyin: "fáng", words: ["房子", "房间"] },
    { char: "屋", pinyin: "wū", words: ["小屋", "屋顶"] },
    { char: "窗", pinyin: "chuāng", words: ["窗户", "窗口"] },
    { char: "桌", pinyin: "zhuō", words: ["桌子", "课桌"] },
    { char: "椅", pinyin: "yǐ", words: ["椅子", "靠椅"] },
    { char: "床", pinyin: "chuáng", words: ["床上", "起床"] },
    { char: "衣", pinyin: "yī", words: ["衣服", "衣裳"] },
    { char: "帽", pinyin: "mào", words: ["帽子", "草帽"] },
    { char: "鞋", pinyin: "xié", words: ["鞋子", "皮鞋"] },
    { char: "饭", pinyin: "fàn", words: ["吃饭", "米饭"] },
    { char: "菜", pinyin: "cài", words: ["青菜", "买菜"] },
    { char: "肉", pinyin: "ròu", words: ["牛肉", "肉类"] },
    { char: "蛋", pinyin: "dàn", words: ["鸡蛋", "鸭蛋"] },
    { char: "果", pinyin: "guǒ", words: ["水果", "结果"] },
    { char: "苹", pinyin: "píng", words: ["苹果"] },
    { char: "桃", pinyin: "táo", words: ["桃子", "桃花"] },
    { char: "瓜", pinyin: "guā", words: ["西瓜", "南瓜"] },
    { char: "豆", pinyin: "dòu", words: ["豆子", "豆浆"] },
    { char: "米", pinyin: "mǐ", words: ["大米", "米饭"] },
    { char: "面", pinyin: "miàn", words: ["面条", "面包"] },
    { char: "茶", pinyin: "chá", words: ["喝茶", "茶叶"] },
    { char: "奶", pinyin: "nǎi", words: ["牛奶", "奶奶"] },
    { char: "糖", pinyin: "táng", words: ["糖果", "白糖"] },
    { char: "蜜", pinyin: "mì", words: ["蜂蜜", "甜蜜"] },
    { char: "鸟", pinyin: "niǎo", words: ["小鸟", "飞鸟"] },
    { char: "鸡", pinyin: "jī", words: ["小鸡", "公鸡"] },
    { char: "鸭", pinyin: "yā", words: ["鸭子", "鸭蛋"] },
    { char: "猫", pinyin: "māo", words: ["小猫", "猫咪"] },
    { char: "狗", pinyin: "gǒu", words: ["小狗", "狗狗"] },
    { char: "马", pinyin: "mǎ", words: ["白马", "马上"] },
    { char: "牛", pinyin: "niú", words: ["黄牛", "牛奶"] },
    { char: "羊", pinyin: "yáng", words: ["小羊", "山羊"] },
    { char: "兔", pinyin: "tù", words: ["兔子", "白兔"] },
    { char: "熊", pinyin: "xióng", words: ["熊猫", "小熊"] },
    { char: "狮", pinyin: "shī", words: ["狮子"] },
    { char: "虎", pinyin: "hǔ", words: ["老虎", "虎王"] },
    { char: "象", pinyin: "xiàng", words: ["大象", "形象"] },
    { char: "猴", pinyin: "hóu", words: ["猴子", "小猴"] },
    { char: "龙", pinyin: "lóng", words: ["飞龙", "龙王"] },
    { char: "画", pinyin: "huà", words: ["画画", "图画"] },
    { char: "歌", pinyin: "gē", words: ["唱歌", "歌曲"] },
    { char: "舞", pinyin: "wǔ", words: ["跳舞", "舞蹈"] },
    { char: "球", pinyin: "qiú", words: ["皮球", "足球"] },
    { char: "戏", pinyin: "xì", words: ["游戏", "戏水"] },
    { char: "真", pinyin: "zhēn", words: ["真正", "认真"] },
    { char: "假", pinyin: "jiǎ", words: ["真假", "放假"] },
    { char: "长", pinyin: "cháng", words: ["长江", "很长"] },
    { char: "短", pinyin: "duǎn", words: ["短小", "长短"] },
    { char: "新", pinyin: "xīn", words: ["新年", "新鲜"] },
    { char: "旧", pinyin: "jiù", words: ["新旧", "旧书"] },
    { char: "冷", pinyin: "lěng", words: ["冷水", "寒冷"] },
    { char: "热", pinyin: "rè", words: ["热水", "热闹"] },
    { char: "早", pinyin: "zǎo", words: ["早上", "早饭"] },
    { char: "晚", pinyin: "wǎn", words: ["晚上", "晚饭"] }
  ],
  "三年级": [
    { char: "智", pinyin: "zhì", words: ["智慧", "聪明"] },
    { char: "慧", pinyin: "huì", words: ["智慧"] },
    { char: "勇", pinyin: "yǒng", words: ["勇敢", "勇气"] },
    { char: "敢", pinyin: "gǎn", words: ["勇敢", "敢说"] },
    { char: "勤", pinyin: "qín", words: ["勤劳", "勤奋"] },
    { char: "劳", pinyin: "láo", words: ["劳动", "劳累"] },
    { char: "诚", pinyin: "chéng", words: ["诚实", "诚心"] },
    { char: "实", pinyin: "shí", words: ["诚实", "实在"] },
    { char: "礼", pinyin: "lǐ", words: ["礼貌", "礼物"] },
    { char: "貌", pinyin: "mào", words: ["礼貌", "面貌"] },
    { char: "团", pinyin: "tuán", words: ["团结", "团体"] },
    { char: "结", pinyin: "jié", words: ["团结", "结果"] },
    { char: "帮", pinyin: "bāng", words: ["帮助", "帮忙"] },
    { char: "助", pinyin: "zhù", words: ["帮助", "助手"] },
    { char: "关", pinyin: "guān", words: ["关心", "关门"] },
    { char: "怀", pinyin: "huái", words: ["关怀", "胸怀"] },
    { char: "感", pinyin: "gǎn", words: ["感动", "感谢"] },
    { char: "谢", pinyin: "xiè", words: ["谢谢", "感谢"] },
    { char: "思", pinyin: "sī", words: ["思想", "思考"] },
    { char: "考", pinyin: "kǎo", words: ["考试", "思考"] },
    { char: "问", pinyin: "wèn", words: ["问题", "提问"] },
    { char: "题", pinyin: "tí", words: ["题目", "问题"] },
    { char: "答", pinyin: "dá", words: ["回答", "答案"] },
    { char: "解", pinyin: "jiě", words: ["解决", "了解"] },
    { char: "知", pinyin: "zhī", words: ["知道", "知识"] },
    { char: "识", pinyin: "shí", words: ["认识", "知识"] },
    { char: "理", pinyin: "lǐ", words: ["道理", "理解"] },
    { char: "解", pinyin: "jiě", words: ["理解", "解开"] },
    { char: "科", pinyin: "kē", words: ["科学", "学科"] },
    { char: "技", pinyin: "jì", words: ["技术", "科技"] },
    { char: "数", pinyin: "shù", words: ["数学", "数字"] },
    { char: "语", pinyin: "yǔ", words: ["语文", "语言"] },
    { char: "文", pinyin: "wén", words: ["文化", "语文"] },
    { char: "英", pinyin: "yīng", words: ["英语", "英雄"] },
    { char: "音", pinyin: "yīn", words: ["音乐", "声音"] },
    { char: "体", pinyin: "tǐ", words: ["体育", "身体"] },
    { char: "育", pinyin: "yù", words: ["教育", "体育"] },
    { char: "美", pinyin: "měi", words: ["美术", "美丽"] },
    { char: "术", pinyin: "shù", words: ["技术", "美术"] },
    { char: "然", pinyin: "rán", words: ["自然", "然后"] },
    { char: "社", pinyin: "shè", words: ["社会", "社区"] },
    { char: "会", pinyin: "huì", words: ["开会", "社会"] },
    { char: "历", pinyin: "lì", words: ["历史", "经历"] },
    { char: "史", pinyin: "shǐ", words: ["历史", "史书"] },
    { char: "地", pinyin: "dì", words: ["地理", "地方"] },
    { char: "球", pinyin: "qiú", words: ["地球", "足球"] },
    { char: "宇", pinyin: "yǔ", words: ["宇宙", "宇航"] },
    { char: "宙", pinyin: "zhòu", words: ["宇宙"] },
    { char: "太", pinyin: "tài", words: ["太阳", "太空"] },
    { char: "阳", pinyin: "yáng", words: ["太阳", "阳光"] },
    { char: "月", pinyin: "yuè", words: ["月亮", "月光"] },
    { char: "星", pinyin: "xīng", words: ["星星", "星球"] },
    { char: "云", pinyin: "yún", words: ["云彩", "白云"] },
    { char: "雷", pinyin: "léi", words: ["打雷", "雷电"] },
    { char: "电", pinyin: "diàn", words: ["电话", "闪电"] },
    { char: "闪", pinyin: "shǎn", words: ["闪电", "闪光"] },
    { char: "雪", pinyin: "xuě", words: ["下雪", "雪花"] },
    { char: "冰", pinyin: "bīng", words: ["冰块", "冰雪"] },
    { char: "森", pinyin: "sēn", words: ["森林"] },
    { char: "林", pinyin: "lín", words: ["树林", "森林"] }
  ]
};

function getChineseList(grade) {
  if (grade && CHINESE_DB[grade]) return CHINESE_DB[grade].slice();
  return Object.keys(CHINESE_DB).reduce(function (acc, g) {
    return acc.concat(CHINESE_DB[g]);
  }, []);
}

function getChineseGrades() {
  return Object.keys(CHINESE_DB);
}
